#!/bin/sh
# this script requires root access

# uninstall theme before installing it again
# we do this to completely refresh content of the folders
./uninstall

# copy theme's folders
cp -rf ./breeze10 /usr/share/plasma/desktoptheme/
cp -rf ./breeze10-dark /usr/share/plasma/desktoptheme/
